### ISSUE TITLE
download link unavailable

### ISSUE THREAD

**Issue by yuexianghubit** [akhilmathurs/libriadapt#6] opened 2024-05-20 09:39 UTC
Hi, thanks for your nice dataset.

Now it seems all the download links are not valid. Could you please help check the reason?

This dataset is the only one that I know of that fits my domain shift on ASR tasks.
Thanks!

**Comment by akhilmathurs** [comment] 2024-05-23 21:39
Thanks for pointing it out. Our hosting website has gone down -- we are looking into it and will update the links once the website issue is fixed.

**Comment by akhilmathurs** [comment] 2024-06-27 09:02
@yuexianghubit, the website is back up and the issue is fixed now.

**Closed as completed by akhilmathurs** 2024-06-27 09:02 UTC
